const pages = {
  index: r => require.ensure([], () => r(require('../pages/index/'))),
  userList: r => require.ensure([], () => r(require('../pages/user/userList/'))),
  userInfo: r => require.ensure([], () => r(require('../pages/user/userInfo/'))),
  userDetail: r => require.ensure([], () => r(require('../pages/user/userInfo/userDetail/'))),
  userCheck: r => require.ensure([], () => r(require('../pages/user/userCheck/'))),
  demo: r => require.ensure([], () => r(require('../pages/demo/m1/'))),
  m1_1: r => require.ensure([], () => r(require('../pages/m1/m1_1/'))),
  m1_1_form1: r => require.ensure([], () => r(require('../pages/m1/m1_1/form1'))),
  m1_1_form2: r => require.ensure([], () => r(require('../pages/m1/m1_1/form2'))),
  m1_2: r => require.ensure([], () => r(require('../pages/m1/m1_2/'))),
  m2_1: r => require.ensure([], () => r(require('../pages/m2/m2_1/'))),
  m3_1: r => require.ensure([], () => r(require('../pages/m3/m3_1/'))),
  orderAlive: r => require.ensure([], () => r(require('../pages/order/orderAlive/'))),
  orderFollow: r => require.ensure([], () => r(require('../pages/order/orderFollow/'))),
  orderSignal: r => require.ensure([], () => r(require('../pages/order/orderSignal/'))),
  orderCustomer: r => require.ensure([], () => r(require('../pages/order/orderCustomer/'))),
  signalApplyNew: r => require.ensure([], () => r(require('../pages/signal/signalApply/'))),
  signalApplyCheck: r => require.ensure([], () => r(require('../pages/signal/signalCheck/'))),
  signalFollow: r => require.ensure([], () => r(require('../pages/signal/signalFollow/'))),
  signalList: r => require.ensure([], () => r(require('../pages/signal/signalList/'))),
  agentApply: r => require.ensure([], () => r(require('../pages/agent/agentApply/'))),
  agentCheck: r => require.ensure([], () => r(require('../pages/agent/agentCheck/'))),
  agentList: r => require.ensure([], () => r(require('../pages/agent/agentList/'))),
  accountMTList: r => require.ensure([], () => r(require('../pages/account/accountMTList/'))),
  accountInfoList: r => require.ensure([], () => r(require('../pages/account/accountInfoList/'))),
  accountCommission: r => require.ensure([], () => r(require('../pages/account/accountCommission/'))),
  accountCommissionList: r => require.ensure([], () => r(require('../pages/account/accountCommissionList/'))),
  serverList: r => require.ensure([], () => r(require('../pages/system/server/'))),
  brokerList: r => require.ensure([], () => r(require('../pages/system/broker/'))),
  commissionLevelList: r => require.ensure([], () => r(require('../pages/system/commissionLevel/'))),
  dictionaryList: r => require.ensure([], () => r(require('../pages/system/dictionary/'))),
  permissionResource: r => require.ensure([], () => r(require('../pages/system/permission/resource/'))),
  permissionRole: r => require.ensure([], () => r(require('../pages/system/permission/role/'))),
  roleResource: r => require.ensure([], () => r(require('../pages/system/permission/roleResource/'))),
  roleResourceDetail: r => require.ensure([], () => r(require('../pages/system/permission/roleResource/roleResourceDetail/'))),
  permissionUserRole: r => require.ensure([], () => r(require('../pages/system/permission/userRole/')))
}

export default pages
